version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - tomas-stefano
  - brenetic
  - mattempty
  - njseeto
  ignore:
  - dependency-name: rspec-rails
    versions:
    - 4.1.1
  - dependency-name: rails
    versions:
    - 6.1.2
  - dependency-name: database_cleaner
    versions:
    - 1.99.0
    - 2.0.0
  - dependency-name: bootsnap
    versions:
    - 1.6.0
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - tomas-stefano
  - brenetic
  - mattempty
  - njseeto
  ignore:
  - dependency-name: ruby
    versions:
    - 3.0.0.pre.alpine3.12
    - 3.0.1.pre.alpine3.12
