version: 2
jobs:
  test:
    working_directory: ~/circle
    docker: &ecr_base_image
      - image: $AWS_ECR_ACCOUNT_URL
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: make spec
          command: make spec
  build_and_deploy_to_test:
    working_directory: ~/circle/git/fb-user-datastore
    docker: *ecr_base_image
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "9f:66:01:8b:19:3c:0e:40:6f:b8:e0:11:a4:43:09:af"
      - run:
          name: checkout fb-user-datastore-deploy
          command: "GIT_SSH_COMMAND='ssh -v -i ~/.ssh/id_rsa_9f66018b193c0e406fb8e011a44309af -o \"IdentitiesOnly=yes\"' git clone git@github.com:ministryofjustice/fb-user-datastore-deploy.git ~/circle/git/fb-user-datastore-deploy"
      - run:
          name: persist git crypt key to disk
          command: "echo $ENCODED_GIT_CRYPT_KEY | base64 -d > /root/circle/git_crypt.key"
      - run:
          name: unlock git crypt
          command: "cd ~/circle/git/fb-user-datastore-deploy && git-crypt unlock /root/circle/git_crypt.key"
      - run:
          name: npm install
          command: 'npm install'
      - setup_remote_docker
      - run:
          name: build and push docker images
          command: './scripts/circleci_build.sh test'
      - run:
          name: deploy to test dev
          command: './scripts/circleci_deploy.sh test dev $KUBE_TOKEN_TEST_DEV'
      - run:
          name: deploy to test production
          command: './scripts/circleci_deploy.sh test production $KUBE_TOKEN_TEST_PRODUCTION'
  build_and_deploy_to_live:
    working_directory: ~/circle/git/fb-user-datastore
    docker: *ecr_base_image
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "9f:66:01:8b:19:3c:0e:40:6f:b8:e0:11:a4:43:09:af"
      - run:
          name: checkout fb-user-datastore-deploy
          command: "GIT_SSH_COMMAND='ssh -v -i ~/.ssh/id_rsa_9f66018b193c0e406fb8e011a44309af -o \"IdentitiesOnly=yes\"' git clone git@github.com:ministryofjustice/fb-user-datastore-deploy.git ~/circle/git/fb-user-datastore-deploy"
      - run:
          name: persist git crypt key to disk
          command: "echo $ENCODED_GIT_CRYPT_KEY | base64 -d > /root/circle/git_crypt.key"
      - run:
          name: unlock git crypt
          command: "cd ~/circle/git/fb-user-datastore-deploy && git-crypt unlock /root/circle/git_crypt.key"
      - run:
          name: npm install
          command: 'npm install'
      - setup_remote_docker
      - run:
          name: build and push docker images
          command: './scripts/circleci_build.sh live'
      - run:
          name: deploy to live dev
          command: './scripts/circleci_deploy.sh live dev $KUBE_TOKEN_LIVE_DEV'
      - run:
          name: deploy to live production
          command: './scripts/circleci_deploy.sh live production $KUBE_TOKEN_LIVE_PRODUCTION'
  build_and_deploy_to_pentest:
    working_directory: ~/circle/git/fb-user-datastore
    docker: *ecr_base_image
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "9f:66:01:8b:19:3c:0e:40:6f:b8:e0:11:a4:43:09:af"
      - run:
          name: checkout fb-user-datastore-deploy
          command: "GIT_SSH_COMMAND='ssh -v -i ~/.ssh/id_rsa_9f66018b193c0e406fb8e011a44309af -o \"IdentitiesOnly=yes\"' git clone git@github.com:ministryofjustice/fb-user-datastore-deploy.git ~/circle/git/fb-user-datastore-deploy"
      - run:
          name: persist git crypt key to disk
          command: "echo $ENCODED_GIT_CRYPT_KEY | base64 -d > /root/circle/git_crypt.key"
      - run:
          name: unlock git crypt
          command: "cd ~/circle/git/fb-user-datastore-deploy && git-crypt unlock /root/circle/git_crypt.key"
      - run:
          name: npm install
          command: 'npm install'
      - setup_remote_docker
      - run:
          name: build and push docker images
          command: './scripts/circleci_build.sh pentest'
      - run:
          name: deploy to pentest dev
          command: './scripts/circleci_deploy.sh pentest dev $KUBE_TOKEN_PENTEST_DEV'
      - run:
          name: deploy to pentest production
          command: './scripts/circleci_deploy.sh live production $KUBE_TOKEN_PENTEST_PRODUCTION'

  trigger_acceptance_tests:
    docker:
      - image: circleci/ruby:latest
    steps:
      - run:
          name: "Trigger Acceptance Tests"
          command: "curl -u ${CIRCLE_TOKEN}: -X POST https://circleci.com/api/v2/project/github/ministryofjustice/fb-acceptance-tests/pipeline -H 'Content-Type: application/json' -H 'Accept: application/json'"

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - trigger_acceptance_tests:
          requires:
            - test
          filters:
            branches:
              only: master
      - build_and_deploy_to_test:
          requires:
            - test
          filters:
            branches:
              only: master
      - build_and_deploy_to_pentest:
          requires:
            - test
          filters:
            branches:
              only: master
      - confirm_live_deploy:
          type: approval
          requires:
            - build_and_deploy_to_test
      - build_and_deploy_to_live:
          requires:
            - confirm_live_deploy
