apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: fb-datastore-cron-db-sweeper-{{ .Values.environmentName }}
  namespace: formbuilder-platform-{{ .Values.environmentName }}
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: fb-user-datastore-api-{{ .Values.environmentName }}
            image: "754256621582.dkr.ecr.eu-west-2.amazonaws.com/formbuilder/fb-user-datastore-api:{{ .Values.circleSha1 }}"
            args:
            - /bin/sh
            - -c
            - bundle exec rails runner 'DbSweeper.new.call'
            securityContext:
              runAsUser: 1001
            imagePullPolicy: Always
            envFrom:
              - configMapRef:
                  name: fb-user-datastore-api-env-{{ .Values.environmentName }}
            env:
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: rds-instance-formbuilder-user-datastore-{{ .Values.environmentName }}
                    key: url
              - name: SECRET_KEY_BASE
                valueFrom:
                  secretKeyRef:
                    name: fb-user-datastore-api-secrets-{{ .Values.environmentName }}
                    key: secret_key_base
              - name: SERVICE_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: fb-platform-datastore-token-{{ .Values.environmentName }}
                    key: token
              - name: SENTRY_DSN
                valueFrom:
                  secretKeyRef:
                    name: fb-user-datastore-api-secrets-{{ .Values.environmentName }}
                    key: sentry_dsn
          restartPolicy: Never
