kind: Service
apiVersion: v1
metadata:
  name: "fb-user-datastore-api-svc-{{ .Values.environmentName }}"
  labels:
    app: "fb-user-datastore-api-{{ .Values.environmentName }}"
    appGroup: "fb-user-datastore"
spec:
  ports:
    # TODO: internal https-only
  - port: 80
    name: http
    targetPort: 3000
  selector:
    app: "fb-user-datastore-api-{{ .Values.environmentName }}"
